#!/bin/sh

echo "SOM Dashboard initialization"

ip=""
python_path=""
queryip() {
    echo -n "waiting for IP address."
    for i in {1..20}
    do
        echo -n "."
        ip=`ifconfig eth0 | grep -oP 'inet \d+\.\d+\.\d+\.\d+' | cut -d ' ' -f2`
        [ ! -z "$ip" ] && break
        sleep 2
    done
}

querypath() {
    echo -n "waiting for path"
    for i in {1..20}
    do
        echo -n "."
        python_path=`python3 -m site | grep packages |grep usr | sed 's/,//g' |sed 's/ //g'| sed 's/^.//;s/.$//'`
        [ ! -z "$python_path" ] && break
        sleep 2
    done
}

DAEMON="bokeh"
DAEMON_ARGS=""
PIDFILE="/var/run/${DAEMON}.pid"



start ()
{
 echo " Starting $DAEMON"
 queryip
 querypath
 if [ -z $ip] || [ -z $python_path ]; then
     echo " TIMEOUT cant find ip addr or python path"
     exit 1
 else
      DAEMON_ARGS=" serve --show --allow-websocket-origin=$ip:5006 $python_path/som-dashboard/"
      echo "start-stop-daemon -S -m -p $PIDFILE -x $DAEMON -- $DAEMON_ARGS"
      start-stop-daemon -S -m -p $PIDFILE -x $DAEMON -- $DAEMON_ARGS&
 fi
}
stop ()
{
 echo " Stoping $DAEMON"
 # start-stop-daemon -K -x $DAEMON
 start-stop-daemon -K -q -p $PIDFILE

}
restart()
{
 stop
 start
}
[ -e $DAEMON ]
 case "$1" in
     start)
	 start; ;;
     stop)
	 stop; ;;
     restart)
	 restart; ;;
     *)
	 echo "Usage: $0 {start|stop|restart}"
	 exit 1
 esac
exit $?
